[build]
  command = """
    npm install && pip install -r requirements.txt
  """
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["python-bridge"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  framework = "#custom"
  command = "python -m uvicorn api.main:app --reload"
  targetPort = 8000
  port = 8888
  publish = "public"
  autoLaunch = true
