services:
  - type: web
    name: social-content-generator
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        value: postgresql://social_content_generator_db_user:Ehfjyr9ogZLqUdntmVCrCMkQFBTqIcqE@dpg-cu6griaj1k6c73f7ce2g-a/social_content_generator_db
      - key: TWITTER_CLIENT_ID
        value: R2pjMnZONWw2dnpCcEJoNHdqSDE6MTpjaQ
      - key: TWITTER_CLIENT_SECRET
        value: cklCaHWUw1MDS3naHZd9BTPf2xn9dCczAU4kL1uQJzpNPzLjhP
      - key: TWITTER_BEARER_TOKEN
        value: AAAAAAAAAAAAAAAAAAAAAGc%2FyAEAAAAAIwk4MWfZdxQcust%2FSCd%2B58l7GCY%3DJEQAXPGjGjpg2uDs9LSYVDCYMSEZUiAYIWvRfN5qlCZVYMmymX
      - key: TWITTER_REDIRECT_URI
        value: https://social-content-generator.onrender.com/auth/twitter/callback
      - key: TWITTER_CALLBACK_URL
        value: https://social-content-generator.onrender.com/auth/twitter/callback
      - key: LINKEDIN_CLIENT_ID
        value: 78h44a7lolh0fa
      - key: LINKEDIN_CLIENT_SECRET
        value: WPL_AP1.VQFNDLP21qQ5yPOY.zjs8HA==
      - key: LINKEDIN_REDIRECT_URI
        value: https://social-content-generator.onrender.com/auth/linkedin/callback
