services:
  - type: web
    name: social-content-generator
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://social_content_generator_user:pass_1234@dpg-cm1aqcud3nmc73f9b6p0-a.oregon-postgres.render.com:5432/social_content_generator?sslmode=require
      - key: TWITTER_CLIENT_ID
        value: R2pjMnZONWw2dnpCcEJoNHdqSDE6MTpjaQ
      - key: TWITTER_CLIENT_SECRET
        value: cklCaHWUw1MDS3naHZd9BTPf2xn9dCczAU4kL1uQJzpNPzLjhP
      - key: TWITTER_BEARER_TOKEN
        value: AAAAAAAAAAAAAAAAAAAAAGc%2FyAEAAAAAIwk4MWfZdxQcust%2FSCd%2B58l7GCY%3DJEQAXPGjGjpg2uDs9LSYVDCYMSEZUiAYIWvRfN5qlCZVYMmymX
      - key: TWITTER_REDIRECT_URI
        value: https://echo-wind.onrender.com/platforms/twitter/callback
      - key: TWITTER_CALLBACK_URL
        value: https://echo-wind.onrender.com/platforms/twitter/callback
      - key: LINKEDIN_CLIENT_ID
        value: 78h44a7lolh0fa
      - key: LINKEDIN_CLIENT_SECRET
        value: WPL_AP1.VQFNDLP21qQ5yPOY.zjs8HA==
      - key: LINKEDIN_REDIRECT_URI
        value: https://echo-wind.onrender.com/auth/linkedin/callback
